name: max_way_flutter
description: This app max way clone flutter
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.1
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  floor: ^1.4.1
  get_it: ^7.2.0
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  flutter_staggered_grid_view: ^0.6.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.1
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0
  json_annotation: ^4.0.1
  json_serializable: ^6.5.4

flutter:


  uses-material-design: true
  assets:
    - asset/images/
